/*Header******************************************************/
// LCD module connections
sbit LCD_RS at RB4_bit;
sbit LCD_EN at RB5_bit;
sbit LCD_D4 at RB0_bit;
sbit LCD_D5 at RB1_bit;
sbit LCD_D6 at RB2_bit;
sbit LCD_D7 at RB3_bit;
sbit LCD_RS_Direction at TRISB4_bit;
sbit LCD_EN_Direction at TRISB5_bit;
sbit LCD_D4_Direction at TRISB0_bit;
sbit LCD_D5_Direction at TRISB1_bit;
sbit LCD_D6_Direction at TRISB2_bit;
sbit LCD_D7_Direction at TRISB3_bit;
// End LCD module connections
const unsigned short TEMP_RESOLUTION = 9;
char *text = "000";
unsigned temp;
void Display_Temperature(unsigned int temp2write) {
    const unsigned short RES_SHIFT = TEMP_RESOLUTION - 8;
    char temp_whole;
    unsigned int temp_fraction;
    temp_whole = (temp2write/8) >> RES_SHIFT ;
    if (temp_whole/100)
        text[0] = temp_whole/100 + 48;
    else
        text[0] = '0';
    text[1] = (temp_whole/10)%10 + 48;
    text[2] = temp_whole%10 + 48;
    Lcd_Out(1, 7, text);
}

void main() {
    ANSEL = 0;
    ANSELH = 0;
    C1ON_bit = 0;
    C2ON_bit = 0;
    PORTA = 0x00;
    TRISA = 0;
delay_ms(100);
switch (PORTA) {
case 0x00: PORTA = 0xFF;
Delay_ms(50);
case 0xFF: PORTA = 0x00; }
    Lcd_Init();
    Lcd_Cmd(_LCD_CLEAR);
    Lcd_Cmd(_LCD_CURSOR_OFF);
  Lcd_Cmd(_LCD_CLEAR);
    Lcd_Chr(1,1,' ');
    Lcd_Chr(1,2,' ');
    Lcd_Chr(1,3,' ');
    Lcd_Chr(1,4,'M');
    Lcd_Chr(1,5,'o');
    Lcd_Chr(1,6,'d');
    Lcd_Chr(1,7,'u');
    Lcd_Chr(1,8,'l');
    Lcd_Chr(1,9,'o');
    Lcd_Chr(1,10,' ');
    Lcd_Chr(1,11,' ');
    Lcd_Chr(1,12,'d');
    Lcd_Chr(1,13,'e');
    Lcd_Chr(1,14,' ');
    Lcd_Chr(1,15,' ');
    Lcd_Chr(1,16,' ');
    Lcd_Chr(2,1,'C');
    Lcd_Chr(2,2,'o');
    Lcd_Chr(2,3,'n');
    Lcd_Chr(2,4,'t');
    Lcd_Chr(2,5,'r');
    Lcd_Chr(2,6,'o');
    Lcd_Chr(2,7,'l');
    Lcd_Chr(2,8,' ');
    Lcd_Chr(2,9,'d');
    Lcd_Chr(2,10,'e');
    Lcd_Chr(2,11,' ');
    Lcd_Chr(2,12,'C');
    Lcd_Chr(2,13,'e');
    Lcd_Chr(2,14,'l');
    Lcd_Chr(2,15,'d');
    Lcd_Chr(2,16,'a');
         Delay_ms(500);
 Lcd_Cmd(_LCD_CLEAR);
    Lcd_Chr(1,1,'C');
    Lcd_Chr(1,2,'o');
    Lcd_Chr(1,3,'n');
    Lcd_Chr(1,4,'t');
    Lcd_Chr(1,5,'r');
    Lcd_Chr(1,6,'o');
    Lcd_Chr(1,7,'l');
    Lcd_Chr(1,8,' ');
    Lcd_Chr(1,9,'d');
    Lcd_Chr(1,10,'e');
    Lcd_Chr(1,11,' ');
    Lcd_Chr(1,12,'C');
    Lcd_Chr(1,13,'e');
    Lcd_Chr(1,14,'l');
    Lcd_Chr(1,15,'d');
    Lcd_Chr(1,16,'a');
    Lcd_Chr(2,1,'T');
    Lcd_Chr(2,2,'e');
    Lcd_Chr(2,3,'r');
    Lcd_Chr(2,4,'m');
    Lcd_Chr(2,5,'o');
    Lcd_Chr(2,6,'e');
    Lcd_Chr(2,7,'l');
    Lcd_Chr(2,8,'e');
    Lcd_Chr(2,9,'c');
    Lcd_Chr(2,10,'t');
    Lcd_Chr(2,11,'r');
    Lcd_Chr(2,12,'i');
    Lcd_Chr(2,13,'c');
    Lcd_Chr(2,14,'a');
    Lcd_Chr(2,15,' ');
    Lcd_Chr(2,16,' ');
         Delay_ms(500);
  Lcd_Cmd(_LCD_CLEAR);
    Lcd_Chr(1,1,'T');
    Lcd_Chr(1,2,'e');
    Lcd_Chr(1,3,'r');
    Lcd_Chr(1,4,'m');
    Lcd_Chr(1,5,'o');
    Lcd_Chr(1,6,'e');
    Lcd_Chr(1,7,'l');
    Lcd_Chr(1,8,'e');
    Lcd_Chr(1,9,'c');
    Lcd_Chr(1,10,'t');
    Lcd_Chr(1,11,'r');
    Lcd_Chr(1,12,'i');
    Lcd_Chr(1,13,'c');
    Lcd_Chr(1,14,'a');
    Lcd_Chr(1,15,' ');
    Lcd_Chr(1,16,' ');
    Lcd_Chr(2,1,' ');
    Lcd_Chr(2,2,' ');
    Lcd_Chr(2,3,' ');
    Lcd_Chr(2,4,' ');
    Lcd_Chr(2,5,' ');
    Lcd_Chr(2,6,' ');
    Lcd_Chr(2,7,' ');
    Lcd_Chr(2,8,' ');
    Lcd_Chr(2,9,' ');
    Lcd_Chr(2,10,' ');
    Lcd_Chr(2,11,' ');
    Lcd_Chr(2,12,' ');
    Lcd_Chr(2,13,' ');
    Lcd_Chr(2,14,' ');
    Lcd_Chr(2,15,' ');
    Lcd_Chr(2,16,' ');
         Delay_ms(500);
  Lcd_Cmd(_LCD_CLEAR);
     Lcd_Out(1, 1, " Temp: ");
    Lcd_Chr(1,10,223);
    Lcd_Chr(1,11,'C');
    Lcd_Chr(1,12,' ');
    Lcd_Chr(1,13,' ');
    Lcd_Chr(1,14,' ');
    Lcd_Chr(1,15,' ');
    Lcd_Chr(1,16,' ');
    do {
        Ow_Reset(&PORTE, 2);
        Ow_Write(&PORTE, 2, 0xCC);
        Ow_Write(&PORTE, 2, 0x44);
        Delay_us(120);
        Ow_Reset(&PORTE, 2);
        Ow_Write(&PORTE, 2, 0xCC);
        Ow_Write(&PORTE, 2, 0xBE);
        temp = Ow_Read(&PORTE, 2);
        temp = (Ow_Read(&PORTE, 2) << 8) + temp;
    Lcd_Chr(2,1,' ');
    Lcd_Chr(2,2,'T');
    Lcd_Chr(2,3,'R');
    Lcd_Chr(2,4,'E');
    Lcd_Chr(2,5,'Y');
    Lcd_Chr(2,6,' ');
    Lcd_Chr(2,7,'-');
    Lcd_Chr(2,8,' ');
    Lcd_Chr(2,9,'I');
    Lcd_Chr(2,10,'s');
    Lcd_Chr(2,11,'o');
    Lcd_Chr(2,12,' ');
    Lcd_Chr(2,13,'C');
    Lcd_Chr(2,14,'Y');
    Lcd_Chr(2,15,'Y');
    Lcd_Chr(2,16,'Z');
        Display_Temperature(temp);
        Delay_ms(500);
    } while (1);
}
